GET http://localhost:3000/expenses/statistics
content-type: application/json
Authorization: Bearer eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMjU2R0NNIn0.x2SAOdYRvi7hPHIV3ZdKBedPARhIXAYS5EocNyjs6RlIgxd_jMPkjNsG4BKw-OXH6_MK9NNoVLz2MstRelBfIjFdBnxPh9PpFpuOtSEM1v2BaCRF1GqeCloGbXN3cbbS4PZCkfr7L_tOo53PaHFfEwo6DE72sfKJWCmPtEDCSG6PvRmwDzGlyD1WRsD-PauN-KJekHjOAom1UEi-J4dgX7WWkTAK6EEIBtjnWttkkvhCerQ5QnfRIG8ACqBwL1_kWAvtoULaFK66c02ojJ0OcfYYR2U66D1bAy1VlM9l7ZzNW1hNPEeWptumFaRvd2Mp--Qt3ptpVbdDubxJaMWmeg.kxDYX8JlnkPb1Qu_.foJhHX5zNOvp-ujI1MmT46uzr6wmV2jDX4YT4wVOEX7zgKAsB6Z_yZss42HGeYDoxPijubc1HBMTrR7WNZzlnjq6u-4WoYJm5KpJefyGdOV_RXiDlpIhxLn2M2plyJLiN6Pd9AvdD6g.ahlP1wPzV-pXg6sKjdZ9Ig
