POST http://localhost:3000/check-user-jwe-token
content-type: application/json
Authorization: Bearer eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMjU2R0NNIn0.t_T_R5cXpJn4CpdIDMnmj5GSFhhquUw0tK6Brrzn2kM9-vw2MXLQpGZrmmrgUHMik0lM2rx44AWCXD074CCPbo7QhBWy9nuvWViRQAjbe7863OCpciUPRt7UvcwZXGF6eTeOGS5xh0eRzGbT0ij0QX1aBZEiSKFQw33YRbi_b3y6odr9xc0PMsqP37bXhjoAH_JfBByNNHUe05b4dSfQQ8cd8ZkgVhe_bKsdVVI0Ew7tysJmS4gnRNcLzuLzmDpWzQTxyvSwc2ybWXYzKpKJbHLaB4_euSdxeokb8f_GQoCtVGccTWFd950vV8wrDWiuK7e32aVXFjJhFduQR_DHqg.e0zSUCDecKcX2Rif.YcBNE9dpxBHqH0YPV3qBBjYlMlhjxZv24vFRcfyJNqK2I3JZ9w0-lJ5Yu2P8wRQjiV8zM06QLZX5Q5y1Y-A0gHzvpetfa719CWxry07v1WheqggQFyZbhDaDR3fqL1iKJIKf-Eaml72n964Y8AxdfGE.YS_jsXxV_vUHaKsjGOE9lw
